### ISSUE TITLE
Not a bug but a general question.

### ISSUE THREAD

**Issue by Jacob-Suldaan** [FTBTeam/FTB-Builders-Paradise#1]
Sorry if this is stupid but i really do not know how to find what mod makes these red squares on item slots, I would like to disable it if possible.

Showing what i mean:
https://gyazo.com/68236b76c9bd88ff69e71ad8b5b3c689

**Comment by Ludi87** [comment]
Quark, you should be able to change it in its options in the Client section - "Slot Transfer Highlight"

**Comment by Sunekaer** [comment]
Ill disable this next update

**Comment by Jacob-Suldaan** [comment]
Thats not necessary i can just disable it, im sure there are people who like having it.
Thanks though!

**Comment by Jacob-Suldaan** [comment]
Also, is there a reason why translocators or extra utilities isnt in the pack until tesslocator has been finished, im on about cause the fluid or advanced ones say there disabled until there finished.

**Comment by Jacob-Suldaan** [comment]
I have found a bug now though.
the things in thaumcraft eep disapearing on the tables research table and arcane workbench, i have to close and reopen them to get them back but it happens again after a little while, here is a gyazo gif of it happening:
https://gyazo.com/29a7c9c4b2c7bc8d555c455e9e543334

**Comment by Sunekaer** [comment]
Please keep it to one bug per issue..
extra utilities is not in because there is nothing special needed from the mod that thermal other one of the other mods cant do

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2707967
