### ISSUE TITLE
Lag/Resource usage issue

### ISSUE THREAD

**Issue by DraxxisMC** [FTBTeam/FTB-Builders-Paradise#10]
* **Modpack Version**: 1.0.0

* **Issue**: Insane usage of resources and lag for a modpack with 147 mods. Random FPS Drops, long loading, freezing when joining server.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Every time I load the pack
* **Mod/s Affected**: 

* **Known Fix**: 

I'm sorry if this doesnt belong here as it isnt really a bug, but man running this with an i7-8700 and 6gb of ram dedicated (out of 16) and the pack just shouldn't be this laggy.

**Comment by Sunekaer** [comment]
Thats weird, im running fine on a lot older CPU and with same amount of ram, do you have the same issue in Singleplayer? do you have a GPU?

**Comment by DraxxisMC** [comment]
Yeah, full setup is i7-8700, 16GB DDR4 2666,  GTX 1070. I run other bigger packs just fine, just this one.

**Comment by Sunekaer** [comment]
Do it happen on a new single player world?

**Comment by XerShade** [comment]
What is your mip maps set too, some mods don't like certain gpus with mip maps on. Try disabling them and see if that helps.

I had this issue with an old pack, my older computer was fine but people with a lot better computers were lagging, and it was a tiny pack like this one.

**Comment by geekcreampuff** [comment]
I'm having the same problem too
