### ISSUE TITLE
My small feedback on the modpack's 1.0.0 version

### ISSUE THREAD

**Issue by RockCat89** [FTBTeam/FTB-Builders-Paradise#11]
First of all, bedrock generated in ovewrworld isn't flat, quite easly fixed fortuantely.

Gendustry should be added for next relase, Binnie mod has genes but it's nice to have an alternative.

And maybe some books written about less known mods, like xencraft for example.
Something short like saying what the mod does in less than 10 sentences.

**Comment by Sunekaer** [comment]
Flat bedrock sure
Gendustry is it really needed, when you have Binnie?
XenCraft should have all information needed in JEI, what other information do you need?

**Comment by RockCat89** [comment]
Gendustry is a good alternative to Binnie genetics, it also provides some tools that make genetics much easier and a lot more fun. 

And i might've worded myself poorly, My example was xencraft because that was first mod i've seen and did not know about before, i wanted all less known mods to have some information on them, tough you are right, JEI should be enough to explain how stuff is working, and there are always tutorials somewhere on youtube or in vast spaces of internet.

**Comment by Sunekaer** [comment]
Okay ill have a think about it.

If you find any lesser known mods that needs info, we can add that via a information tab in JEI, but most of the mods in this park is pretty known or very easy to use

**Comment by RockCat89** [comment]
Today i played the pack a bit more than before
I've noticed that quick/fast leaf decay also seems to be missing
Veinmater/orexcavator would also be a nice addition to the pack if they aren't there yet (i played on creative)
Thanks for creating this awesome pack :)

**Comment by Sunekaer** [comment]
OreExcavation is in already

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2707967
