### ISSUE TITLE
unable to craft mining dim portal

### ISSUE THREAD

**Issue by RasiergummiBlei** [FTBTeam/FTB-Builders-Paradise#14]
* **Modpack Version**: 
1.0.0
playing on server
* **Issue**: 
I cant craft mining dim portal from yamda
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**:  yamda

* **Known Fix**:

**Comment by Sunekaer** [comment]
Unable to craft how? the crafting recipe doesnt work? or you cant enter the mining dim?

**Comment by Sunekaer** [comment]
Hmm, i just tested in Single Player and on server, i dont have this issue, could you check with the people running the server that they havent removed the recipe?
