### ISSUE TITLE
Mod request: Funky Locomotion so that there are options to create non-static buildings. 

### ISSUE THREAD

**Issue by Electrofried** [FTBTeam/FTB-Builders-Paradise#15]
Would it be possible to get funky locomotion or similar mod that adds added frames to the pack?
I am aware that I can just add it myself but it makes joining/hosting servers an issue to change mods in packs.    
The mod itself is fairly light and should have minimal impact on performance, however it adds so many possibilities. One of the joys of building in modded for myself and many people is the ability to make very interactive bases. Funky locomotion gives players many more options for making moving buildings, doors, walls and even whole buildings in modded that are just not possible with the limitations of vanilla pistons and redstone.  It would be great to see it included in such a fantastic building pack.   

Trains (Railcraft / Immersive Railroading) or even basic signals (Signals) for trains would also be nice, but I feel that has a more limited appeal with the first two mods adding a fair amount of overhead to the pack and is probably a separate issue.   
Thanks!

**Comment by Sunekaer** [comment]
Adding Funky Locomotion in next update, gonna be a no to the other once

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2710721
