### ISSUE TITLE
Energy Condenser not working

### ISSUE THREAD

**Issue by Djmnecraft** [FTBTeam/FTB-Builders-Paradise#16]
When I try to use the energy condenser it won't let me put items in and whatever item I hover over in my inventory it replaces the top slot. Also, it is filled with red squares for some reason. Any help/ suggestions would be greatly appreciated because I just want to get back to building.

**Comment by Sunekaer** [comment]
What items are you trying to put in?

**Comment by Eremithius** [comment]
I was experiencing a similar issue, however upon looking at it a bit closer it does allow you to put items in, but the UI does not update in a way that represents what is actually happening.

**Comment by Sunekaer** [comment]
So its the UI there doesnt update correctly? if so please report that here: https://github.com/sinkillerj/ProjectE/issues
