### ISSUE TITLE
EqualDragons disables Quark's Dragon Scale drop

### ISSUE THREAD

**Issue by iNko97** [FTBTeam/FTB-Builders-Paradise#17]
EqualDragons sets the dragon's flag FirstDragon as true, that means that it disables the Dragon Scale drop from quark (To craft elytras) and moreover it drops a ton of xp. To fix it in eqdrag config there's an option Egg Only

Thanks!

**Comment by Sunekaer** [comment]
Good to know, will get this changed in next update, thank you

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2710721
