### ISSUE TITLE
Rustic Grapes

### ISSUE THREAD

**Issue by ashboy3093** [FTBTeam/FTB-Builders-Paradise#18]
* **Modpack Version**: 1.0.0

* **Issue**: Once Rustic Grapes start to grow I get a CCL exception error and the game crashes

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/618d0b5f

* **Is it Repeatable?**: Yes. I currently can't even log into that save due to it,

* **Mod/s Affected**: Rustic

![crash](https://user-images.githubusercontent.com/16342369/57656832-299e4980-759f-11e9-9e9e-b76b41d79901.PNG)

**Comment by Sunekaer** [comment]
Hm thats one i havent seen before, could you try updating and test with version 1.2.0, before we try other stuff

**Comment by ashboy3093** [comment]
I still get the same error. I was able to stay in longer this time and noticed that the lattice I was using to hold the string is broken but the string with grapes is still there. But as soon as I moved I got disconnected. The CCL exception happened as soon as I logged in. This is with the updated 1.2.0.
![newcrash](https://user-images.githubusercontent.com/16342369/57741468-963e4480-7682-11e9-8211-c236ded3bcf3.PNG)

 https://paste.feed-the-beast.com/view/de8cd201

**Comment by Sunekaer** [comment]
Okay thanks ill report it to the mod author 
You can try this:
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then you need to create a issue on darkutils github and get help from them

**Comment by Lectorel** [comment]
I'm having the same issue here.

**Comment by ashboy3093** [comment]
I tried to config change as well to see if it would fix and as soon as I turn to the direction of the grape leaves they will cause a CCL error and crash.

**Comment by Yhuxz** [comment]
> Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then you need to create a issue on darkutils github and get help from them

**If you're talking about this two:**

    # Set this to true to remove any Entity that throws an error in its update method 

instead of closing the server and reporting a crash log. BE WARNED THIS COULD 

SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE 

FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method 

instead of closing the server and reporting a crash log. BE WARNED THIS COULD 

SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE 

FOR DAMAGES.
    B:removeErroringTileEntities=true

it doesn't removed it and crashed again, I have the same issue in a client server without using a modpack

**Comment by 016Nojr** [comment]
Pack update coming in a few days, the issue should be fixed then.
