### ISSUE TITLE
[Feature request] Add EMC to values to Blizz, Blitz and Basalz rods

### ISSUE THREAD

**Issue by Mac15001900** [FTBTeam/FTB-Builders-Paradise#19]
Those are currently very difficult to obtain in large quantities (e.g. for setting up a viaduct network), basically requiring multiple mob farms in specific biomes. It would make much more sense for them to be obtainable from EMC.

A value of 3072 (double that of Blaze rods, since those are more easily farmable) would probably be appropriate.

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2713666
