### ISSUE TITLE
Weird crash on startup

### ISSUE THREAD

**Issue by jk1895** [FTBTeam/FTB-Builders-Paradise#2]
I never saw such a crash with Minecraft. Don't know what's wrong with my PC, but I can load every other pack!

* **Modpack Version**: 1.0.0

* **Issue**: game crashes while loading

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/726a3f9d

* **Is it Repeatable?**: every time I load the game

* **Mod/s Affected**: ?

* **Known Fix**: ?

**Comment by LeoCTH** [comment]
Blame Java. Seems like a JVM failure.

**Comment by Sunekaer** [comment]
Your using an old java version
1. You will need to open the Twitch App, and head to the Settings.  This is the cogwheel in the lower left corner of the app.
2. This will open up your Settings options.  Click on the Minecraft tab.
3. Scroll down to LAUNCH METHOD.
4. Change it from Native Launcher to Jar Launcher.  Try which ever version of Java you have installed, if you don't have Java installed already please do so at this time.  If that doesn't work:
- check to make sure you have the newest version
- try with a 64 bit version

**Comment by jk1895** [comment]
Adding the 64 bit version helped.
Thanks a lot.
