### ISSUE TITLE
Crash (possible Forestry issue)

### ISSUE THREAD

**Issue by cxav12** [FTBTeam/FTB-Builders-Paradise#21]
* **Modpack Version**: 1.20

* **Issue**: The issue originally started on 1.1.0. I was going to excavate blue leaves from a tree with a tinkers mattock containing a silky jewel. As soon as I hit the button to excavate the leaves, the game crashed. I tried upgrading to version 1.2.0 to see if that helped fix the issue, but now I can't even get to the main screen. The game just crashes now while it's loading half way. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ac74a5a4

* **Is it Repeatable?**: Not sure. I'm unable to get back into my world.

* **Mod/s Affected**: I believe the issue is with Forestry

* **Known Fix**: No clue!

**Comment by Sunekaer** [comment]
Thanks ill report the log to Forestry

To get back in to your world, you can try this:
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then you need to create a issue on darkutils github and get help from them

**Comment by cxav12** [comment]
My world is still crashing. Do you know where I can find darkutils github?
Thanks!

**Comment by Sunekaer** [comment]
https://github.com/Darkhax-Minecraft/Dark-Utilities/issues

**Comment by temp1011** [comment]
This is fixed in forestry (https://github.com/ForestryMC/ForestryMC/commit/29c7d1eaf080b90449910a0f5bc24187ed58af5f) so the latest version shouldn't have this problem any more.
