### ISSUE TITLE
Halted Start up

### ISSUE THREAD

**Issue by ALLICE** [FTBTeam/FTB-Builders-Paradise#22]
* **Modpack Version**: 1.2.0

* **Issue**: Startup gives me a "your mod loader has malfunctioned because mods are missing"

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2d7018d0

* **Is it Repeatable?**: easily, by starting the game up.

* **Mod/s Affected**: Biomesoplenty 1.12.2-7.0.1.2438-universal jar (x2)
emc builder wand : emcbuilderswand (x2)
fast furnace : fast furnace (x2)
ftblib : ftb lib (x2)
quark : quark (x2)
simplylight : simplylight 0.6.0/0.7.0 (x2)

* **Known Fix**: (removing the conflicting mods does not work)

**Comment by Sunekaer** [comment]
Try reinstalling the pack
