### ISSUE TITLE
Items with EMC unable to be learned

### ISSUE THREAD

**Issue by RikSharp** [FTBTeam/FTB-Builders-Paradise#24]
Some items with EMC (buckets with thermal foundation liquids, upgraded machines) will not be learned by the transmutation table. Instead, it just eats the item.

* **Modpack Version**: 1.1.0

* **Issue**: Some items with EMC (buckets with thermal foundation liquids, upgraded machines) will not be learned by the transmutation table. Instead, it just eats the item.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: Project E, Project EX, Thermal Foundation

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Ah yeah that is do to NBT tages on the items, those i items need nbt removed. please lot me know  if you find more

**Comment by Sunekaer** [comment]
Regrading the "upgraded" machines, that also because of NBT so if i remove from the "upgraded" version it will also be removed from the basic one

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2713666
