### ISSUE TITLE
[Mod Request] JEI Bees

### ISSUE THREAD

**Issue by ChachavaMC** [FTBTeam/FTB-Builders-Paradise#25]
Apologies if this is not the right place for this as it's not technically a bug

Breeding trees (and I would assume bees as well but I haven't used these) is a little bit of a pain at the moment as when you try to find the mutations needed to get a particular tree JEI presents you with 60 or so pages, covering every possible mutation. Searching through all of the mutations is very time consuming. Adding in the JEI Bees mod would limit the mutations shown to just the sapling you're searching for. This would be a very handy addition.

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2713666
