### ISSUE TITLE
[Mod Request] Bibliocraft

### ISSUE THREAD

**Issue by Jadziyah** [FTBTeam/FTB-Builders-Paradise#26]
Bibliocraft has been a staple of Minecraft decorators for years. It offers unique storage/display blocks- (ie potions, books, items, etc), unique mechanics (typsetting table book copying, mobs using typewriters, modular seats), and tons of variety to build with. The mod would be appreciated and used by many players in this pack especially!

**Comment by Sunekaer** [comment]
We are not looking to add anymore mods to the pack, unless it for bug fixing or JEI addons/information

**Comment by kellyraeu** [comment]
Jadziyah, I downloaded Bibliocraft to my Twitch folder under Instances and then Mods. It runs fine so far as part of the pack.
