### ISSUE TITLE
My keys movement get an issue since i install this modspack

### ISSUE THREAD

**Issue by PauMS** [FTBTeam/FTB-Builders-Paradise#27]
Hi,

Well, in fact I got 2 issues :
1. my character get stuck (can't moove) during some seconds.
2. my character strafe right (or left, i don't remember) by himself.
I don't understand how it happens.
Worse, it also happened on the other game (Apex Legends) i played the next day (it's yesterday).

I uninstalled the modspack and since, my key movements are under control.

Maybe it could be in cause :
When i launched the modspack for the first time I was playing AL.
And the launch had an error 2 or 3 times in a row.

That's all!

**Comment by Sunekaer** [comment]
Well, i cant really do anything about this when you also have this issue in other games..

**Comment by PauMS** [comment]
Well, but it comes with the mods pack and goes when i deleted the mods pack.

**Comment by Sunekaer** [comment]
I have asked around, no one have seen this issue before and don’t know what could be causing it

**Comment by PauMS** [comment]
Ok, I am not surprised. All unknown bugs are for me .. xD
Thanks dude!

I will reinstall it and launch it without playing another game at the same time.
Maybe it will work ... I guess.

**Comment by PauMS** [comment]
So, I just re-install the modspack and launch it ...

As the first time, the game crash during launching. It happened twice.
U can access both crash reports [here ](https://drive.google.com/open?id=1clQUwjEKIAtxETMORxJOsxBHLRGzO_yB) and [here](https://drive.google.com/open?id=1NPXDo1pvzzNoFxeRbDfUZMUgvRWVnvU6)

No time to play nao so see u next wkd (maybe) to give u a new feedback.

Cheers

**Comment by Sunekaer** [comment]
Your using an old java version

You will need to open the Twitch App, and head to the Settings. This is the cogwheel in the lower left corner of the app.
This will open up your Settings options. Click on the Minecraft tab.
Scroll down to LAUNCH METHOD.
Change it from Native Launcher to Jar Launcher. Try which ever version of Java you have installed, if you don't have Java installed already please do so at this time. If that doesn't work:
check to make sure you have the newest version
try with a 64 bit version

**Comment by RevDragonus** [comment]
i have experienced this issue PauMS is having. it is not minecraft but his computer. when i have had this issue in minecraft, the way i fix it is to just hit ESC press the 6 directional keys and ESC again to return to the game, problem solved everytime. i have done the same thing in other games when it happens and same result, fixed.
