### ISSUE TITLE
Dragon Egg does't respawn

### ISSUE THREAD

**Issue by iNko97** [FTBTeam/FTB-Builders-Paradise#3]
There is no way to obtain the dragon egg, since it does not respawn slaying the dragons after the first one. Is it possible to implement the respawn? It is a nice decorative block :)

Inko

**Comment by Sunekaer** [comment]
reminder to myself. https://minecraft.curseforge.com/projects/equaldragons

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2707967
