### ISSUE TITLE
"Quark's" Limestone Tools Uncraftable

### ISSUE THREAD

**Issue by HuskyNator** [FTBTeam/FTB-Builders-Paradise#30]
version 1.2.0

Unable to craft any of the limestone tools from the mod "Quark", though they show in the NEI recipes. This was on a standard FTB Builder's Paradise server, on which none of the members were able to craft these recipes either. Thus very repeatable.

Mod: "Quark r1.5-150"
No known fix.

**Comment by Sunekaer** [comment]
What are these tools called? i dont think any tools when searching limestone

**Comment by HuskyNator** [comment]
The standard stone tools from vanilla minecraft, sorry for my unclearness.
