### ISSUE TITLE
Creosote Oil Clay Buckets stuck in ME Drive

### ISSUE THREAD

**Issue by stevepitchy** [FTBTeam/FTB-Builders-Paradise#31]
* **Modpack Version**: <Builders Paradise 1.0>

* **Issue**: <I placed 5 clay buckets of cresote oil into my ME Drive. Now I cannot remove them. Clicking, right-clicking, shift-right-clicking do nothing. They are stuck>
->

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Ceramics, Applied Energistics 2, Immersive Engineering

**Comment by Sunekaer** [comment]
Seems to be a problem with all Clay buckets containing liquid

**Comment by Sunekaer** [comment]
doesnt happen when only having
"appliedenergistics2-rv6-stable-6.jar and Ceramics-1.12-1.3.7.jar"
needs more testing

**Comment by Sunekaer** [comment]
I have disable all clay buckets so this wont happen in the future, those in your system i cant do anything about

**Comment by stevepitchy** [comment]
Thank you! I thought it happens with regular buckets too?
