### ISSUE TITLE
Right click stone stairs consumes item in hand - stairs become snow covered (who can make that up!)

### ISSUE THREAD

**Issue by stevepitchy** [FTBTeam/FTB-Builders-Paradise#32]
* **Modpack Version**: Builders Paradise 1.0

* **Issue**:  I was scanning the world with the Thaumonimeter. When I scanned cobblestone stairs my Thaumometer disappeared from my hand and the stair became snow covered from Snow Variants Mod. Then I tried other items in hand and the same thing happens.

* **Link to Log or Crash File Paste**: 
* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: All
* **Known Fix**: none

**Comment by Sunekaer** [comment]
#9 update your pack
