### ISSUE TITLE
Can't make molten pig iron in Tinker's Smelter

### ISSUE THREAD

**Issue by Cubeportal** [FTBTeam/FTB-Builders-Paradise#33]
For some reason i can't seem to be able to make Molten Pigiron in the Tinker's Smelter. The smelter was working fine before.

JEI says it needs 144mb of iron, 40 blood and 72mb of molten clay, I've got 600mb of lava and I've got all the ingredients as seen below.

https://i.imgur.com/Rd3qOTI.png
https://i.imgur.com/HJ9jKkf.png
https://i.imgur.com/aC0iv4v.png

I've got heaps of free space as well.

**Comment by Sunekaer** [comment]
hmm it works just fine for me :/ 
![image](https://user-images.githubusercontent.com/18720460/58383446-22336300-7fd7-11e9-931b-70dad6d2872d.png)
