### ISSUE TITLE
Thaumcraft amber bearing ore not generating

### ISSUE THREAD

**Issue by ValentineBlaze** [FTBTeam/FTB-Builders-Paradise#35]
* **Modpack Version**: 1.0.0 and 1.2.0

* **Issue**: Thaumcrafts ore isnt generating and it wil not work with the biomes o plenty amber ore at all and prevents progress in thaumcraft. ive looked and searched for the ore and tested with the biomes to see if it would work to create things but it doesnt seem to.

* **Mod/s Affected**: so its thaumcraft 6 and biomes o plenty that seem to have a conflict

**Comment by BamBamBiim** [comment]
you can make this ore with botania orechid flower.

**Comment by Sunekaer** [comment]
Fix in next update it will spawn in new generated chunks, plus added a conversion recipe from BoP amber to TC amber and back
