### ISSUE TITLE
Please add a way to transmit power

### ISSUE THREAD

**Issue by JoshuaWalsh** [FTBTeam/FTB-Builders-Paradise#36]
I'm really enjoying this modpack. I'm playing it with my girlfriend and we are trying to live up to the name of the modpack by focussing on making everything we build somehow aesthetically pleasing. Our builds are spread across the map, each area serving a different purpose. We have a Simple Teleporters network joining them together.

A challenge we are running into is power generation. In some areas it is easy to make power generation that fits in with the theme (a windmill in our farm area, generators in our industrial area, etc...) but in other areas power generation doesn't really fit but we still want to be able to connect our AE2 network.

We've noticed that the modpack includes the Tesslocators mod, but sadly this mod appears to be completely unfinished. Of the 6 blocks in Tesslocators only one of them works and the others are disabled due to being incomplete. This means there is no easy way to create a power network.

Could you please add a mod like Flux Networks or RFTools, at least until Tesslocators is a bit closer to production-ready? RFTools Dimensions also looks pretty cool and might fit in with the theme of this modpack.

**Comment by Sunekaer** [comment]
Tesslocators has been updated with basic and advanced power Tesslocator.
Any issues found with them please report at https://github.com/LatvianModder/Tesslocator/issues

**Comment by RevDragonus** [comment]
Flux Network would definately be an asset to this pack. My friends and i are doing the same thing on a server with having themed areas. Sticking to build styles and power in many areas is a bit challenging.
