### ISSUE TITLE
Crash on startup on 1.3.0

### ISSUE THREAD

**Issue by PABessero** [FTBTeam/FTB-Builders-Paradise#38]
* **Modpack Version**: FTB Builders Paradise 1.3.0

* **Issue**: Crash on startup since ~ a few hours (used to work)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/9a5c7a01

* **Is it Repeatable?**: Yes, everytime i launch the pack (both with and without Optifine)

* **Mod/s Affected**: Currently no idea

* **Known Fix**:

**Comment by Sunekaer** [comment]
Try deleting options.txt in Instances\FTB Builders Paradise

**Comment by PABessero** [comment]
Yup, worked, huge thanks!
