### ISSUE TITLE
Mod Request: Immersive Tech

### ISSUE THREAD

**Issue by YOYOK9** [FTBTeam/FTB-Builders-Paradise#39]
the Mod: https://minecraft.curseforge.com/projects/immersive-tech

Seeing that Immersive Engineering is in the pack was wondering if Immersive Tech could be added. It is a power generation mod add-on for Immersive Engineering that gives players more options for power, as well as some higher output generators for big tech builds or AE2 systems.

**Comment by Sunekaer** [comment]
Hi YOYOK9 

Thanks for the suggestion, but we are not looking to add more mods to the pack unless its for fixing bugs

**Comment by YOYOK9** [comment]
All good. I fully understand not wanting too add more bugs to the soup ;)
