### ISSUE TITLE
EMC Builders Wand crash

### ISSUE THREAD

**Issue by ChachavaMC** [FTBTeam/FTB-Builders-Paradise#4]
* **Modpack Version**: 1.0.0

* **Issue**: Attempting to craft the EMC Builders Wand crashes the pack, Reloading the world and entering the GUI of the crafting station with the items in also causes the crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1651fcd4 : This is the second crash log after entering the crafting station GUI

* **Is it Repeatable?**: Yes, each time I attempt to craft the wand or enter the GUI with the ingredients for it in there

* **Mod/s Affected**: EMC Builders Wand

**Comment by Sunekaer** [comment]
Thanks for the report, ill try and get hold of the mod author and get it fixed

**Comment by aoyuka102** [comment]
I can craft it but it doesn't have a tooltip and  not working

**Comment by FusionLord** [comment]
This has been fixed in version 1.4. https://minecraft.curseforge.com/projects/emc-builders-wand/files/2707282

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2707967
