### ISSUE TITLE
Recipe Conflicts

### ISSUE THREAD

**Issue by Jadziyah** [FTBTeam/FTB-Builders-Paradise#40]
I've found multiple recipe conflicts in the pack. So far:

- The 'glass slabs' from _Vanilla Builders Extension_ (any color) default to 'Colored block thin' from _Little Tiles_

- The 'leaf wall' (any variety) from _Vanilla Builders Extension_ default to corresponding 'hedge' from _MrCrayfish's Furniture Mod_

Will update if I find more

**Comment by Sunekaer** [comment]
> The 'glass slabs' from Vanilla Builders Extension (any color) default to 'Colored block thin' from Little Tiles

I only have this issue with using White Stained glass to make Glass slabs, not any color?
> The 'leaf wall' (any variety) from Vanilla Builders Extension default to corresponding 'hedge' from MrCrayfish's Furniture Mod

Ty

**Comment by Jadziyah** [comment]
> > The 'glass slabs' from Vanilla Builders Extension (any color) default to 'Colored block thin' from Little Tiles
> 
> I only have this issue with using White Stained glass to make Glass slabs, not any color?
> 

Ah good!
