### ISSUE TITLE
Modpack crashing on start of world

### ISSUE THREAD

**Issue by IcyTooNicy** [FTBTeam/FTB-Builders-Paradise#41]
I have not experienced this before in any modpack. Any help would be appreciated.

* **Modpack Version**:  1.3.0 

* **Issue**: I stopped playing for the night all things normal and I try to rejoin the world and it keeps crashing. I tried using the JAR launcher I tried to do the repair thing I tried to do everything I knew which granted is not a lot.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/3c4d1763 

* **Is it Repeatable?**: Yes it happens every time I try playing

* **Mod/s Affected**: No idea

* **Known Fix** Nope

**Comment by Sunekaer** [comment]
Seem that the file has been corrupted or overwritten with a blank file.
I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the issue.
