### ISSUE TITLE
Astral and Quark Recipe Conflicts

### ISSUE THREAD

**Issue by RevDragonus** [FTBTeam/FTB-Builders-Paradise#42]
* **Modpack Version**: 1.3.0

* **Issue**: Quartz Crafting Table shares same recipe as Marble Brick from Astral Sorcery. Astral Sorcery Marble Stair (brick varient) share the same recipe as Quark Marble Stair (solid marble varient) making it so you cant make Marble Stair from Astral Sorcery. Because some of the recipe conflicts, making multi block structures from Astral will not register as complete. 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Astral Sorcery, Quark, Marble Crafting Table

**Comment by Sunekaer** [comment]
>  Quartz Crafting Table shares same recipe as Marble Brick from Astral Sorcery.
 
Fixed in dev

> Astral Sorcery Marble Stair (brick varient) share the same recipe as Quark Marble Stair (solid marble varient) making it so you cant make Marble Stair from Astral Sorcery. Because some of the recipe conflicts, making multi block structures from Astral will not register as complete.

These all use marble from different mods in my testing? you can use a chisel to make AS marble in to Quark or Chisel marble
