### ISSUE TITLE
Want to use Shader but cant :c

### ISSUE THREAD

**Issue by AdrianDieDose** [FTBTeam/FTB-Builders-Paradise#43]
* **Modpack Version**:  1.3.0 

* **Issue**: Hey i wanted to know if anyone can help me to make optifine work in this MP bc i want some nice looking shader for my builds?
The newest Optifine version works but the sun follows my cursor 🌵  

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yeah

* **Mod/s Affected**:

* **Known Fix**: No

**Comment by Sunekaer** [comment]
Hmm dont know, and we dont support Optifine, try on Optifine´s issue tracker
