### ISSUE TITLE
Startup Failure.

### ISSUE THREAD

**Issue by Nicole-Evermore** [FTBTeam/FTB-Builders-Paradise#44]
* **Modpack Version**: 1.4.0

* **Issue**: Pack fails during initialization in both native and jar launchers

* **Link to Log or Crash File Paste**: https://pastebin.com/wRyWgaXq FTB's paste server is down as I post this, I apologize.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Seems to fail during Astral Sorcery, but I'm not sure.

* **Known Fix**: None

**Comment by Sunekaer** [comment]
Try reinstalling the pack

**Comment by kalanihelekunihi** [comment]
It would seem this issue is caused when having a newer jre version installed. The error message states that certain calls were deprecated in jre8.
If you install jre8, this pack works properly.
