### ISSUE TITLE
[Issue] Coagulated Blood w/ Tinker's doesn't complete

### ISSUE THREAD

**Issue by dstephens1980** [FTBTeam/FTB-Builders-Paradise#45]
Pouring blood from Smeltery into the casting table starts the recipe for Coagulated Blood but never completes.  Using latest Builder's Paradise build.

Steps to reproduce:
Smelt rotten flesh into blood in Smeltery
Pour blood into Casting Table
Wait

**Comment by Sunekaer** [comment]
Works just fine for me in my world, are you playing on server or have modified the pack in anyway?

**Comment by dstephens1980** [comment]
My apologies on the late reply, stock FTB server installed via CubeCoder's AMP frontend running in a Docker container.  Logs do not reveal any issues or errors related to the reported issue.

**Comment by dstephens1980** [comment]
I will attempt to get a video of the issue when I get home.
