### ISSUE TITLE
My character is in a constant movement, and after a while it starts flinging me across the world

### ISSUE THREAD

**Issue by Nitro137** [FTBTeam/FTB-Builders-Paradise#46]
* **Modpack Version**: 1.4.0

* **Issue**: Well, I join any world and for some reason, my character is moving all over the place, at first I walk normally but after a while, it starts to fling me across my world, and I don't know how to stop it.

* **Link to Log or Crash File Paste**: I don't crash

* **Is it Repeatable?**: It happens every time

* **Mod/s Affected**: don't know if it affects any mods

* **Known Fix**: don't know

![1](https://user-images.githubusercontent.com/51927158/59627651-bdb68000-910c-11e9-98a3-18ef61b0de9b.PNG)
![2](https://user-images.githubusercontent.com/51927158/59627653-be4f1680-910c-11e9-8dc1-b5030d1f5eaa.PNG)
![3](https://user-images.githubusercontent.com/51927158/59627658-c018da00-910c-11e9-966e-8f8e3ff9dedb.PNG)

**Comment by Sunekaer** [comment]
Did you change any setting for BetterFPS?
Minecraft\Instances\FTB Builders Paradise\config\betterfps.json
Make sure it has these settings `{"algorithm":"rivens-half","updateChecker":false,"preallocateMemory":false,"fog":true,"beaconBeam":true,"fastHopper":true,"fastBeacon":false,"fastSearch":true,"asyncSearch":true}`

**Comment by Nitro137** [comment]
ok, let me check, but I didn't touch the settings before and it still did it.

**Comment by Nitro137** [comment]
It works
