### ISSUE TITLE
Min RAM?

### ISSUE THREAD

**Issue by RudyTheNinja** [FTBTeam/FTB-Builders-Paradise#48]
Sorry, couldn't find a way to just send you a message, so here I am :D
From twitch/curse launcher, was just wondering what the RAM req is to run this game
I couldn't find it in the description

I got a few users who can't run anything over a certain amount and would like to make sure they can participate
Yes I can have them DL it and test it but that depends on how long it takes to DL and then launch
We've tried that with another modpack b4 and it ended up just upsetting the user

Would be cool if you could add it to the description 👍
![Capture2](https://user-images.githubusercontent.com/45320386/60387757-fa636f00-9a5c-11e9-87e5-7be95d0c4dc1.PNG)

**Comment by Sunekaer** [comment]
A general rule for 1.12.2 packs is min 4GB of ram, and that also applies for this pack.

**Comment by megs2** [comment]
I'm new to this and I wanted to know if there was a way I could check how much ram I have available and also how I can add more to make it work? if that makes sense?
