### ISSUE TITLE
Game crash when clicking on beacon

### ISSUE THREAD

**Issue by rubyrose96** [FTBTeam/FTB-Builders-Paradise#49]
* **Modpack Version**: 1.5.0

* **Issue**: Game crashing to launcher whenever i click on a beacon

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/5751188e

* **Is it Repeatable?**: every time i click on a beacon

**Comment by egypt** [comment]
Same happening here. Crash log looks the same. This makes it impossible to progress in Botania.

**Comment by Sardly01234** [comment]
same here!

**Comment by Oshroth** [comment]
In my case, the crash was caused by Quark. It looks like you need to update to at least Quark 162 to fix the beacon crash.

**Comment by egypt** [comment]
Confirmed that updating Quark fixes the issue. Thanks, @Oshroth !
