### ISSUE TITLE
Bug connecting to a server

### ISSUE THREAD

**Issue by kogapegaz** [FTBTeam/FTB-Builders-Paradise#5]
Modpack Version: 1.0.0 (Recommended)

Issue: I can join my friends on her server. It was a bug with the client, he not found mods on client 

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/058d3967

Is it Repeatable?: yes at each connection

Mod/s Affected: ?

Known Fix: ?

**Comment by Sunekaer** [comment]
You trying to join a server running another pack then this one

**Comment by kogapegaz** [comment]
yes indeed there was a huge misunderstanding thank you. I will play the other mode pack with my friends but I will still play yours too because it is interesting
