### ISSUE TITLE
Last Stand death check ignores armor and EPF damage reduction

### ISSUE THREAD

**Issue by AureusVulpes** [FTBTeam/FTB-Builders-Paradise#50]
* **Modpack Version**: Builder's Paradise 1.4 and 1.5 (reverified after update)

* **Issue**: Last Stand is supposed to save the player from lethal damage at the cost of EXP. In the case of most damage, this works fine. However, in the case of extreme damage (that extreme armor totals from mods like Astral Sorcery are necessary to counter damage totals from mods like Tinker's Construct and even just fall damage), Last Stand seems to only be checking the base damage of the source, rather than the damage after all reduction calculations, such as Armor or EPF from various Protection enchants. (more on this in the reproduction section)

* **Link to Log or Crash File Paste**: This bug doesn't result in a crash, it just deletes your health bar and EXP.

* **Is it Repeatable?**: A friend and I have very different builds on Astral Sorcery. He focuses heavily on armor and HP, and i focus on a general increase of ability (speed, some armor, damage, etc). He has ~52 armor and 25 HP, and i have around 21 armor and the base HP of 20. You might think this is the source of the problem, but uncharged Creepers should not be capable of oneshotting me through more than double armor than a Diamond set *AND* Protection 16 (4*4) on Normal difficulty, plus loss of a quantity of EXP, when i routinely survive such encounters on vanilla hardcore with bland diamond armor and EPF16 with minimal HP loss.

My high-tinkered sword would oneshot me with my armor on, but not him wearing my armor. We swapped out armor, piece by piece with armor that was fundamentally identical, just without Last Stand. When the final Last stand piece was removed and replaced with one that did not have it, I survived with a small HP loss. The cause of him surviving seemed to be that his extra 5 HP gave him more than my sword's base damage. We calculated it out, and sure enough, my sword would hit an unarmored target for roughly 24.2 damage, roughly 1 HP less than he had. 

NOTE: This would happen even when he was at less than Max HP, even down into the -teens, so I can only assume there is some max HP check going wonky. Through a lot of tinkering with tinker's construct (about an hour's worth), we slowly upgraded a sword to deal more and more damage until it deleted my HP bar: it jumped from dealing just over 2 damage with 2 TC's 'Sharp' to Last Stand "saving me" with TC 'Sharper', which is a very small damage increase.

* **Mod/s Affected**: Most mods that add armor will make this enchant seem less than useful as it negates all survivability enhancements in the face of high damage output and reduces combat to "your exp meter is now your health bar"

* **Known Fix**: Would recommend verifying/changing when Last Stand does its damage to current hp comparison. I would also see about checking any max HP checks the enchant does, and making sure this checks against an armor-reduced value as well.

**Comment by Sunekaer** [comment]
Sorry for the late reply, life been busy..
I cant do anything about this, i would recommend reporting it to OpenBlocks as they are adding the Enchantment
