### ISSUE TITLE
Outrageous load time/ Not Responding Error, 2 hour loadup time

### ISSUE THREAD

**Issue by TheMightyMcGrew** [FTBTeam/FTB-Builders-Paradise#53]
* **Modpack Version 1.5.0**: 

* **Issue**: So loading this pack is proving to be a bear of a task, it all loads super smooth until 6/7 on the last bit. the middle loading bar shows its trying to load JEI and is around 17/115 I think? Anyhow at this point it comes to a complete stop and the program stops responding. This can be waited out but it will take an hour or two to do this. My system specs are more than capable of handling this modpack, its just loading the dang thing. If there is anything I can provide other than a crash report, because as stated theres not been a crash yet, Id be happy to offer it.
No crash, but still an issue worth noting

* **Is it Repeatable?**: Every time I start the pack

* **Mod/s Affected**: JEI? Im not sure really, just going off where it stops loading and responding

* **Known Fix**: Wait an hour and a half (not exaggerating)

**Comment by Sunekaer** [comment]
i load the pack in like 5-7min, maybe more ram or your pc is to slow idk..
