### ISSUE TITLE
Graphics suddently start Crashing

### ISSUE THREAD

**Issue by grp1604** [FTBTeam/FTB-Builders-Paradise#56]
So when i got on my singleplayer world (in which LAN was opened) i went to the Twilight Forest. At the moment that i got inside it, i found the place where Naga spawns and suddently my graphics start crashing whenever i move my mouse. Not sure which mod could be causing this and this has never happened in other modpack or in [vanilla.] Down here are some of those examples of it. I hope anyone could help me.

![example1](https://user-images.githubusercontent.com/52866178/61175739-6d67fc00-a5ac-11e9-94ad-ee8bf1a88131.png)

![example2](https://user-images.githubusercontent.com/52866178/61175748-98eae680-a5ac-11e9-9000-6881624e3a62.png)

* **Modpack Version**: FTB Builders Paradise version 1.5.0

* **Issue**: Graphics suddently crash 

* **Is it Repeatable?**: Yes. Even in the overworld it keeps the same problem

**Comment by 016Nojr** [comment]
Pack update coming in a few updates, please check if you still have the issue as there's been a few updates after this, I've never seen this before.
