### ISSUE TITLE
Cannot summon Botania Gaia

### ISSUE THREAD

**Issue by UniBBGcorN** [FTBTeam/FTB-Builders-Paradise#58]
* **Modpack Version**:1.5.0 

* **Issue**:just cannot summon the gaia no matter how much space i provide 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Does it give any message in chat or what happens when you try to spawn it?
