### ISSUE TITLE
Is the fluid Tesslocators activated in the pack?

### ISSUE THREAD

**Issue by Jacob-Suldaan** [FTBTeam/FTB-Builders-Paradise#59]
* **Modpack Version**: 1.5.0

* **Issue**: I can't find the recipe for Tesslocators fluid version.

* **Link to Log or Crash File Paste**: there isnt one

* **Is it Repeatable?**: -

* **Mod/s Affected**: Tesslocators

* **Known Fix**: -

**Comment by Sunekaer** [comment]
Basic are, but advanced isnt as the dev hasnt finished them
