### ISSUE TITLE
Bug with Thaumcraft

### ISSUE THREAD

**Issue by Jacob-Suldaan** [FTBTeam/FTB-Builders-Paradise#6]
I have found a bug.
the things in the Thaumcraft tables keep disapearing like the scribing tools and paper from the research table and all the vis for the arcane workbench, I have to close and reopen them to get them back but it happens again after a little while, here is a gyazo gif of it happening:
https://gyazo.com/29a7c9c4b2c7bc8d555c455e9e543334

* **Modpack Version**: 1.0.0

* **Issue**: Disapearing items.

* **Link to Log or Crash File Paste**: it isnt anything that would produce this.

* **Is it Repeatable?**: yeah look at the GIF I attached and thats what keeps happening.

* **Mod/s Affected**: Thaumcraft.

* **Known Fix**: VERY temp fix is to close and reopen the Thaumcraft table your in.

**Comment by Sunekaer** [comment]
Please open the pack and recreate this bug, then go to the log folder in the pack folder and copy the content of  latest.log and paste it on http://paste.feed-the-beast.com click create and send the link here

**Comment by Jacob-Suldaan** [comment]
my log: https://paste.feed-the-beast.com/view/f38403b5

**Comment by 016Nojr** [comment]
Pack update coming in a few updates, neither Tinkers or Thaumcraft is getting updates for 1.12 anymore so if it's still there it unfortunately wont be fixed.
