### ISSUE TITLE
Game crashes on startup, every time

### ISSUE THREAD

**Issue by thegoldenfrog** [FTBTeam/FTB-Builders-Paradise#61]
* **Modpack Version**: 1.5.0

* **Issue**: Game crashes on startup, specifically during phase 2/7 as it starts to load preinitialization for Gendustry

* **Link to Log or Crash File Paste**: http://m.uploadedit.com/bbtc/1564428050896.txt

* **Is it Repeatable?**: Every time I load minecraft.
* **Mod/s Affected**: Gendustry(?)

* **Known Fix**: None

**Comment by Sunekaer** [comment]
Link doesnt work, please reopen ticket with new link to log file if you still have this issue.
