### ISSUE TITLE
Tinkers construct items disappearing

### ISSUE THREAD

**Issue by bradminky** [FTBTeam/FTB-Builders-Paradise#62]
* **1.5**: 

* **Tinkers constuct axes, pickaxes, items disappear when tossed on ground**: 

* **Link to Log or Crash File Paste**: 

* **yes**: 

* **TiC**: 

* **Known Fix**:

**Comment by bradminky** [comment]
other items like pure certus seeds are disappearing when thrown as well

**Comment by Sunekaer** [comment]
Can confirm AE2 seeds are invisible when dropped on the ground, i will try and find out what mod is causing this.

**Comment by 016Nojr** [comment]
I am not able to reproduce this with a new version of the pack that should be out in a few days, if it still exists it's probably caused by a mod that's not getting updates for 1.12.
