### ISSUE TITLE
Game will not launch with mod pack.

### ISSUE THREAD

**Issue by ironkuting** [FTBTeam/FTB-Builders-Paradise#64]
* **Modpack Version**: 1.5.0

* **Issue**: Clicking play closes launcher, game doesn't even pop up and the launcher reopens on the game output tab and ends the process there.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1e39e11e

* **Is it Repeatable?**: Every time I click play on the launcher.

* **Mod/s Affected**: I am unsure what mods are effecting the launch, I haven't added any to it, just updated the pack to the latest version and tried playing it.

* **Known Fix**: Unknown

**Comment by Sunekaer** [comment]
First time seeing this issue and it looks to be an issue with the launcher and not the pack, do you also have the issue with version 1.6 of the pack
