### ISSUE TITLE
"Caught exception from MineTogetherServer"

### ISSUE THREAD

**Issue by KCtops100** [FTBTeam/FTB-Builders-Paradise#65]
* **Modpack Version**: 
1.5.0
* **Issue**: 
Game crashes on singleplayer world load.  This world sometimes is using LAN.
* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/0d0224af
* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 
The crash report notes that MineTogether (minetogether-1.10.2-2.1.3.jar
) is causing the crash.
* **Known Fix**:

**Comment by Aurilett** [comment]
Hopefully there will be an actual resolution, but what worked for me was deleting the config ( .cfg file) and the mod itself from the folder. Hopefully there will be a real solution soon!

**Comment by Sunekaer** [comment]
Should be fixed by the newest version of the mod.
