### ISSUE TITLE
Hay Layer dupes itself when picked up.

### ISSUE THREAD

**Issue by Buzimu** [FTBTeam/FTB-Builders-Paradise#66]
* **Modpack Version**: 1.5.0

* **Issue**: Hay Layer Dupes itself when picked up.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes.  

* **Mod/s Affected**: No additional mods affected.

* **Known Fix**:  N/A

**Comment by Sunekaer** [comment]
Issue reported.
https://github.com/Lothrazar/DecoLayers/issues/2

**Comment by Jake-E** [comment]
Mod issue fixed in https://github.com/Lothrazar/DecoLayers/pull/3
