### ISSUE TITLE
Botany Flower Spawning Issue

### ISSUE THREAD

**Issue by CakeFlour** [FTBTeam/FTB-Builders-Paradise#69]
While attempting to do the Botany Mod, I ran into a weird occurrence.
Placing down 2 or more flowers onto the Botany soil makes it start Generating a bunch of different higher tier flowers such as Cornflowers at random, with random colors as well. There doesn't seem to be any rhyme or reason to it at all.
The rate of random flower production is high as well, I was able to fill up a standard double chest with flowers within a few in game days.
This has been tested on both a Server, and Single Player, with the same result.
This is frustrating when attempting to collect specific types of flowers.

Modpack: Builder's Paradise 1.5.0 (Minecraft 1.12.2)
Mods: Binnie's Botany

**Comment by 016Nojr** [comment]
Pack update coming in a few days, Binnie's Mods isnt getting updates for 1.12 anymore so if it's still there it unfortunately wont be fixed.
