### ISSUE TITLE
Villagers are invisible

### ISSUE THREAD

**Issue by ThaBazZz** [FTBTeam/FTB-Builders-Paradise#7]
Im not sure if this a bug but i can hear the villagers but they are nowhere to be found..structures from the village also..

**Comment by ThaBazZz** [comment]
Update, i just found an archeologist underground..wich is probably what i heard..still no villages though..
I will keep looking

**Comment by Sunekaer** [comment]
hmm, i see them fine
![image](https://user-images.githubusercontent.com/18720460/57194095-e579cc00-6f42-11e9-91ba-9270a05bef32.png)

**Comment by ThaBazZz** [comment]
must be bad luck on my side then ..

**Comment by TwinkieJean** [comment]
I'm having this issue too.
I can also hear villagers when I'm no where near a village. e.i. in the middle of the ocean.

**Comment by Sunekaer** [comment]
Could you try disabling Dynamic Surroundings and see if its that adding those sounds?

**Comment by ThaBazZz** [comment]
dig down and you should find an geologist from quark that somehow can be heard with allot of blocks in between..

**Comment by Sunekaer** [comment]
Okay so it is just a quark structure that you hear?
