### ISSUE TITLE
Vanilla Tweaks error

### ISSUE THREAD

**Issue by RezziPie** [FTBTeam/FTB-Builders-Paradise#72]
Every time I open a megaloot case I get a "potential problem found" In the upper right corner of the screen it says to hit ctrl+I.  It says: This did not cause a crash, but there will likely still be consequences such as world corruption or broken features.  The following mods have been identified as the potental cause: Vanilla tweaks.

I have the latest update of the RAD modpack -->

It happens every time I open a loot case.

* **Mod/s Affected**: Vanilla tweaks

**Comment by Sunekaer** [comment]
Hi
This tracker is only for FTB Builders paradise, please find the correct tracker for this issue.

Thanks! :)
