### ISSUE TITLE
Quest mode for newbies

### ISSUE THREAD

**Issue by Devs3105** [FTBTeam/FTB-Builders-Paradise#73]
Is it possible to have a quest mode for people who are new to modded Minecraft?
I have downloaded and played some, but most of the mods I don't know and can't find a manual or book to go by.  It is a great idea and I am looking for a modpack just like this.

**Comment by Sunekaer** [comment]
Hi,

There wont be added any quests to this pack, i recommend our pack FTB Academy for people there is new to Modded
