### ISSUE TITLE
Builders Paradise via Twitch, Immersive Engineering steel block problem

### ISSUE THREAD

**Issue by JaysBYWW** [FTBTeam/FTB-Builders-Paradise#74]
Builders Paradise version 15 via Twitch, Immersive Engineering steel block problem.  When making steel blocks - they turn into 'Thermal Expansion' Steel Blocks & the excavator won't transform from blocks.  (the blocks turn into a light-colored smooth grey block)

**Comment by Sunekaer** [comment]
There is a crafting recipe to make a swap between the 2
