### ISSUE TITLE
Not able to take items out of any chest from the bottom right corner

### ISSUE THREAD

**Issue by forthelolzez** [FTBTeam/FTB-Builders-Paradise#75]
* **Modpack Version**: 1.5.0

* **Issue**: Any chest including village blacksmith chests will work properly except for the slots near the bottom right corner where some just can't be taken out and some won't allow me to select them at all, this bug affects all chests from all mods as well as the bag and backpack mods droppers, dispensers, and hoppers work fine. it only seems to affect items with inventories with more than 9 slots. I've also noticed that it happens occasionally in the creative inventory too.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes it has happened across several worlds and startups

* **Known Fix**: it does not occur when not in full screen

**Comment by Sunekaer** [comment]
Hi, 
Im not able to reproduce this issue, if you still have this issue please reopen the ticket with a log fill

Thanks!
