### ISSUE TITLE
AE2 Config Suggestion: MeteoriteWorldGen=true

### ISSUE THREAD

**Issue by jaredbeck** [FTBTeam/FTB-Builders-Paradise#78]
* **Modpack Version**: 1.12.2

* **Issue**: Meteorites are my favorite feature of AE2. I searched for a few hours before realizing that `MeteoriteWorldGen` has been set to `false`. Was this intentional? If so, please feel free to close this issue. If not, may I suggest setting to `true`?

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: AE2

* **Known Fix**: I'm not sure

**Comment by Sunekaer** [comment]
This is intentional :)
