### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ingalls45** [FTBTeam/FTB-Builders-Paradise#79]
[latest.log](https://github.com/FTBTeam/FTB-Builders-Paradise/files/3854873/latest.log)
Version:1.6.1
Everytime I try launching the modpack it will crash, and send me back to the launcher, I have not seen the actual Minecraft loading screen.

**Comment by Sunekaer** [comment]
https://github.com/TheRandomLabs/RandomPatches/issues/63
