### ISSUE TITLE
Server Chunks Not loading

### ISSUE THREAD

**Issue by Mayhem1512** [FTBTeam/FTB-Builders-Paradise#82]
I have setup a server on 2 different computers and give it 12GB of ram and the servers chunks refuse to load for all players.
once you break a block the chunk will load.
This is for local access and external.
any help would be amazing 😀.

**Comment by Mayhem1512** [comment]
https://imgur.com/a/3M8vUpN

Link to screen shots

**Comment by kfsofronas** [comment]
check to make sure that the server itself has the modpack installed. if not, try installing a previous release of the modpack and run that instead.

**Comment by 016Nojr** [comment]
Pack update coming in a few days, please check again to see if it's fixed.
