### ISSUE TITLE
Startup fails every time

### ISSUE THREAD

**Issue by IanGolsby** [FTBTeam/FTB-Builders-Paradise#83]
* **Modpack Version**: 1.6.0

* **Issue**: Every startup leads to the same error, a tweaker class not found

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/089afcd3

* **Is it Repeatable?**: Yes, every time I start pack, including with restarting launcher. Only with this pack

**Comment by Sunekaer** [comment]
Hmm, what launcher are you using? it seems like it cant find some part of Forge
