### ISSUE TITLE
Stuck on Loading Terrain

### ISSUE THREAD

**Issue by QueenDarkness93** [FTBTeam/FTB-Builders-Paradise#85]
I have updated Java, uninstalled and reinstalled all mod packs and programs. This is happening for several people on my server. I am not the server owner though. 

Some people are able to load in no problem others like me were able to for a week and no all of a sudden we cant load in it gets stuck on loading terrain says we joined the game then left the game and we get an error code.

**Comment by vinnyg0621** [comment]
the loader is taking forever for me

**Comment by 016Nojr** [comment]
Seems like something is broken on serverside depending on where you are in the server, so unless you can provide server logs I cant do anything about it.
