### ISSUE TITLE
EMC Builders Wand doesn't work

### ISSUE THREAD

**Issue by FuzzyHarpyBug** [FTBTeam/FTB-Builders-Paradise#87]
![image](https://user-images.githubusercontent.com/74686420/99595692-a0d94880-29a1-11eb-8a66-118bd765fb15.png)

Wand does not function at all unless you have the block you are trying to place in your inventory, and then it uses them like a normal builders wand without using EMC.

**Comment by 016Nojr** [comment]
Pack update coming in a few days, the mod isnt getting updates for 1.12 anymore so if it's still there it unfortunately wont be fixed.
