### ISSUE TITLE
items being absorbed by stairs and slabs

### ISSUE THREAD

**Issue by Voxeltheslime** [FTBTeam/FTB-Builders-Paradise#9]
* ** 1.0.0**: 

* **items being deleted to make snow items that are white color will be deleted whenever you click on a stair or slabs to make snow. this includes tinkers pickaxes backpacks and even snow **: 

* **doesnt create a log or crash**: 

* **this has happened multiple times and im very sad about my pickaxe )T-T)**: 

* ** snow varients **: 

* **get rid of the mod  (or just blacklist stuff that isnt snow)**:

**Comment by Sunekaer** [comment]
Could you show a gif of this issue?

**Comment by XerShade** [comment]
Can confirm this happens, a slab ate my Grand master shuriken when I was hitting a zombie in front of it earlier.

**Comment by Sunekaer** [comment]
What slab? from what mod? i need more information to recreate this issue to find an solution

**Comment by XerShade** [comment]
A vanilla stone slab did it. Not sure what mod is doing this but all I know is my high level shuriken got turned into a snow layer. I'll run to spawn and re-do this in creative to see what mod makes the snow slab appear if I can.

**Comment by XerShade** [comment]
The slab that appeared after eating a cloned shuriken is from "Snow Variants".

**Comment by Pecant-Pie** [comment]
yeah this just happened to me, it happens with stairs too.  It adds a snow cover to the stairs and consumes the item in my hand.

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2710721

**Comment by Voxeltheslime** [comment]
> 
> 
> Could you show a gif of this issue?
https://imgur.com/a/JIOU3wY
