### ISSUE TITLE
A lot of bee's don't work or are useless

### ISSUE THREAD

**Issue by MisterMessias** [FTBTeam/FTB-Builders-Paradise#90]
Refined bee's are in the game and they can make Petroleum Comb but when I try to find PEtroleum Comb in Not Enough Items or in creative mode I can't find it. When I try to put the Pteoleum Comb in the Centrufuge it won't work either. Is this done on purpose or is this a bug?

**Comment by 016Nojr** [comment]
Pack update coming in a few days, the mod isnt getting updates for 1.12 anymore so if it's still there it unfortunately wont be fixed.
